[tool.poetry]
name = "youtube-analytics-project-astakhov"
version = "0.1.0"
description = ""
authors = ["George Astakhov <goha1115@mail.ru>"]
readme = "README.md"
packages = [{include = "youtube_analytics_project_astakhov"}]

[tool.poetry.dependencies]
python = "^3.11"
google-api-python-client = "^2.91.0"
isodate = "^0.6.1"
flake8 = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
